[rule]
# 🚀 节点选择 🇭🇰 香港节点 🇨🇳 台湾节点 🇯🇵 日本节点 🇺🇲 美国节点 🇸🇬 狮城节点 🇰🇷 韩国节点
# 链上の工具
DOMAIN-KEYWORD,gmgn,🚀 节点选择
DOMAIN-KEYWORD,axiom,🚀 节点选择
DOMAIN-KEYWORD,debot,🚀 节点选择
DOMAIN-KEYWORD,bscscan,🚀 节点选择
DOMAIN-KEYWORD,basescan,🚀 节点选择
DOMAIN-KEYWORD,etherscan,🚀 节点选择

# 漏网の网站
DOMAIN-KEYWORD,vercel,🚀 节点选择
DOMAIN-KEYWORD,github,🚀 节点选择
DOMAIN-KEYWORD,appstorrent,🚀 节点选择
DOMAIN-KEYWORD,visualstudio,🚀 节点选择
DOMAIN-KEYWORD,19990908.xyz,🚀 节点选择
DOMAIN-KEYWORD,githubusercontent,🚀 节点选择

# Twitter
DOMAIN-KEYWORD,twitter,🇭🇰 香港节点
DOMAIN-SUFFIX,t.co,🇭🇰 香港节点
DOMAIN-SUFFIX,x.com,🇭🇰 香港节点
DOMAIN-SUFFIX,grok.com,🇭🇰 香港节点
DOMAIN-SUFFIX,twimg.com,🇭🇰 香港节点
DOMAIN-SUFFIX,twitter.com,🇭🇰 香港节点
DOMAIN-SUFFIX,tweetdeck.com,🇭🇰 香港节点

# 禁HK (使用韩国节点)
DOMAIN-KEYWORD,tiktok,🇰🇷 韩国节点
DOMAIN-KEYWORD,truthsocial,🇰🇷 韩国节点

# 交易所
DOMAIN-KEYWORD,bybit,🇰🇷 韩国节点
DOMAIN-KEYWORD,binance,🇰🇷 韩国节点
DOMAIN-KEYWORD,bntrace,🇰🇷 韩国节点
DOMAIN-KEYWORD,bnbstatic,🇰🇷 韩国节点

# Emby
DOMAIN-KEYWORD,yixia,🌍 国外媒体
DOMAIN-KEYWORD,lilyemby,🌍 国外媒体
DOMAIN-KEYWORD,dandanplay,🌍 国外媒体

# 纯净IP (Ai平台)
DOMAIN-KEYWORD,reddit,💬 Ai平台
DOMAIN-KEYWORD,claude,💬 Ai平台
DOMAIN-KEYWORD,google,💬 Ai平台
DOMAIN-KEYWORD,gemini,💬 Ai平台
DOMAIN-KEYWORD,antigravity,💬 Ai平台

# 确保直连
DOMAIN-KEYWORD,oracle,DIRECT

# 确保直连
DOMAIN-SUFFIX,61.com,DIRECT
DOMAIN-SUFFIX,wise.com,DIRECT
DOMAIN-SUFFIX,iflow.work,DIRECT
DOMAIN-SUFFIX,userapi.com,DIRECT
DOMAIN-SUFFIX,miaozhen.com,DIRECT
DOMAIN-SUFFIX,broadcom.com,DIRECT
DOMAIN-SUFFIX,streamlit.app,DIRECT
DOMAIN-SUFFIX,cloudflare.com,DIRECT
DOMAIN-SUFFIX,steamserver.net,DIRECT