[rule]
# 🚀 节点选择 🇭🇰 香港节点 🇨🇳 台湾节点 🇯🇵 日本节点 🇺🇲 美国节点 🇸🇬 狮城节点
# 链上の工具
DOMAIN-KEYWORD,gmgn,🚀 节点选择
DOMAIN-KEYWORD,axiom,🚀 节点选择
DOMAIN-KEYWORD,debot,🚀 节点选择
DOMAIN-KEYWORD,bscscan,🚀 节点选择
DOMAIN-KEYWORD,basescan,🚀 节点选择
DOMAIN-KEYWORD,etherscan,🚀 节点选择

# 漏网の网站
DOMAIN-KEYWORD,github,🚀 节点选择
DOMAIN-KEYWORD,vercel,🚀 节点选择
DOMAIN-KEYWORD,appstorrent,🚀 节点选择
DOMAIN-KEYWORD,visualstudio,🚀 节点选择
DOMAIN-KEYWORD,19990908.xyz,🚀 节点选择
DOMAIN-KEYWORD,githubusercontent,🚀 节点选择

# 禁HK (使用日本节点)
DOMAIN-KEYWORD,tiktok,🇯🇵 日本节点
DOMAIN-KEYWORD,truthsocial,🇯🇵 日本节点

# 交易所
DOMAIN-KEYWORD,bybit,🇯🇵 日本节点
DOMAIN-KEYWORD,binance,🇯🇵 日本节点
DOMAIN-KEYWORD,bntrace,🇯🇵 日本节点
DOMAIN-KEYWORD,bnbstatic,🇯🇵 日本节点

# 纯净IP (Ai平台)
DOMAIN-KEYWORD,reddit,💬 Ai平台
DOMAIN-KEYWORD,claude,💬 Ai平台
DOMAIN-KEYWORD,google,💬 Ai平台
DOMAIN-KEYWORD,gemini,💬 Ai平台
DOMAIN-KEYWORD,antigravity,💬 Ai平台

# 确保直连
DOMAIN-SUFFIX,61.com,DIRECT
DOMAIN-SUFFIX,wise.com,DIRECT
DOMAIN-SUFFIX,iflow.work,DIRECT
DOMAIN-SUFFIX,userapi.com,DIRECT
DOMAIN-SUFFIX,miaozhen.com,DIRECT
DOMAIN-SUFFIX,broadcom.com,DIRECT
DOMAIN-SUFFIX,streamlit.app,DIRECT
DOMAIN-SUFFIX,cloudflare.com,DIRECT

# Emby
DOMAIN-KEYWORD,yixia,DIRECT
DOMAIN-KEYWORD,lilyemby,DIRECT
DOMAIN-KEYWORD,dandanplay,DIRECT