; 链上の工具
rule=DOMAIN-KEYWORD,gmgn,🚀 节点选择
rule=DOMAIN-KEYWORD,axiom,🚀 节点选择
rule=DOMAIN-KEYWORD,debot,🚀 节点选择
rule=DOMAIN-KEYWORD,bscscan,🚀 节点选择
rule=DOMAIN-KEYWORD,basescan,🚀 节点选择
rule=DOMAIN-KEYWORD,etherscan,🚀 节点选择

; 漏网の网站
rule=DOMAIN-KEYWORD,vercel,🚀 节点选择
rule=DOMAIN-KEYWORD,appstorrent,🚀 节点选择
rule=DOMAIN-KEYWORD,visualstudio,🚀 节点选择
rule=DOMAIN-KEYWORD,19990908.xyz,🚀 节点选择

; 禁HK (使用日本节点)
rule=DOMAIN-KEYWORD,tiktok,🇯🇵 日本节点
rule=DOMAIN-KEYWORD,truthsocial,🇯🇵 日本节点

; 交易所
rule=DOMAIN-KEYWORD,bybit,🇯🇵 日本节点
rule=DOMAIN-KEYWORD,binance,🇯🇵 日本节点
rule=DOMAIN-KEYWORD,bntrace,🇯🇵 日本节点
rule=DOMAIN-KEYWORD,bnbstatic,🇯🇵 日本节点

; 纯净IP (Ai平台)
rule=DOMAIN-KEYWORD,github,💬 Ai平台
rule=DOMAIN-KEYWORD,reddit,💬 Ai平台
rule=DOMAIN-KEYWORD,claude,💬 Ai平台
rule=DOMAIN-KEYWORD,google,💬 Ai平台
rule=DOMAIN-KEYWORD,gemini,💬 Ai平台
rule=DOMAIN-KEYWORD,antigravity,💬 Ai平台

; 确保直连
rule=DOMAIN-SUFFIX,61.com,DIRECT
rule=DOMAIN-SUFFIX,wise.com,DIRECT
rule=DOMAIN-SUFFIX,iflow.work,DIRECT
rule=DOMAIN-SUFFIX,userapi.com,DIRECT
rule=DOMAIN-SUFFIX,miaozhen.com,DIRECT
rule=DOMAIN-SUFFIX,broadcom.com,DIRECT
rule=DOMAIN-SUFFIX,streamlit.app,DIRECT
rule=DOMAIN-SUFFIX,cloudflare.com,DIRECT

; Emby
rule=DOMAIN-KEYWORD,yixia,DIRECT
rule=DOMAIN-KEYWORD,lilyemby,DIRECT
rule=DOMAIN-KEYWORD,dandanplay,DIRECT
